spring.application.name=chat-app
spring.data.mongodb.uri=mongodb+srv://CipherCrew:ciphercrew@sublite.4cjuy3h.mongodb.net/cipherchat?retryWrites=true&w=majority&appName=sublite
server.port=8081

# Clerk Configuration
clerk.publishable-key=pk_test_b3JpZW50ZWQtYmFzcy0zOS5jbGVyay5hY2NvdW50cy5kZXYk
clerk.secret-key=sk_test_dTlDXV78f96I7T9r8XVCJlbJHVZ4Ne86qapGH3uli1
